### ISSUE TITLE
MPC-BE auto change launch in FS does not work when rendering HDR video with MPC-VR 

### ISSUE THREAD

**Issue by Fr0stX76** [Aleksoid1978/VideoRenderer#68] opened 2022-11-20 03:17 UTC
Specs:
Windows 10 22H2
Nvidia 3090
Driver 526.98
MPC-BE 1.6.5.3 x64
MPC-VR 0.6.3.1956 x64

The issue I have is that when I open an HDR video (see image attached) rendered by MPC-VR (default options, see attached image) , the auto change display in MPC-BE does not work if the option "launch in Fullscreen" is selected (see attached image). If I remove this option, start the video (in windowed mode), then go to Fullscreen manually, the display switches as expected.

Opening an SDR video (x265 BT709) with the same setup and option work perfectly without having to go to windowed first, it only affect HRD video.

Also using the same setup and options with MPC-BE and Madvr (which I'm trying to move away from...) will work with both HDR and SDR video, so it seems to be pointing at MPC-VR.   

Is this expected? Or maybe there is something I did not setup properly in MPC-BE and/or in MPC-VR?

![MPC-BE Change modejpg](https://user-images.githubusercontent.com/70845235/202880849-45304c95-6f97-4955-94be-b9179c52b9f6.jpg)

![MPC VR settingsjpg](https://user-images.githubusercontent.com/70845235/202880858-015766b7-ddfc-4422-8351-1b4b800fbfab.jpg)

![HDR Video](https://user-images.githubusercontent.com/70845235/202880863-85c91f6e-be6c-46b0-9de1-8c26b3e247d4.jpg)

**Comment by Aleksoid1978** [comment] 2022-11-20 06:19
Devs don't have HDR TV and can't test it.

**Comment by Aleksoid1978** [comment] 2023-01-10 03:01
Try set **Auto Display HDR On/Off** to **used for fullscreen**.

**Comment by DfrostX** [comment] 2023-01-12 02:10
> Try set **Auto Display HDR On/Off** to **used for fullscreen**.

No luck either, launching in FS with **used for fullscreen** option did not work.

The only thing that seems to work is to have this option at "always used", launch windowed and double click to FS. It seems like something goes wrong in the chain when switching from 120hz to 23.976hz + going fullscreen in the player at the same time as the renderer switching HDR to “on”.

Leaving the display at 120hz (so basically not using the "autochange fullscreen monitor mode) does work but the stutters make it unwatchable,

**Comment by clsid2** [comment] 2023-01-12 02:40
It does two switches in this situation, one for the fullscreen mode and one for turning on HDR mode. Looks like the HDR switch is attempted while the fullscreen mode switch is still in progress, hence it fails. Maybe the error code that it returns indicates this situation, and isn't a generic fail. If so, perhaps that could be used to retry after a short pause.

**Comment by Aleksoid1978** [comment] 2023-01-12 12:08
Check.
[mpc-be64.exe.zip](https://github.com/Aleksoid1978/VideoRenderer/files/10401375/mpc-be64.exe.zip)

**Comment by DfrostX** [comment] 2023-01-13 00:39
> Check. [mpc-be64.exe.zip](https://github.com/Aleksoid1978/VideoRenderer/files/10401375/mpc-be64.exe.zip)

Tried this version. With the launch in FS option on, the display now swithes to HDR mode, but does not apply the "autochange fullscreen monitor mode" profile (so the display now stays at 120hz instead of going to 23.976hz).

This behaviour is exactly the same as the older version when I turned off "autochange fullscreen monitor mode"

**Comment by Aleksoid1978** [comment] 2023-01-13 04:01
Well then, it remains to be hoped that the developers may someday have HDR TV ).

**Comment by Aleksoid1978** [comment] 2023-02-01 02:17
I checked - I have the **auto change launch in FS** in the player and **Auto Display HDR On/Off to used for fullscreen** in MPC VR working fine.

**Comment by Aleksoid1978** [comment] 2023-02-01 02:34
I also checked **Use Exclusive fullscreen**.
My MPC VR settings:
![MPCVR](https://user-images.githubusercontent.com/11625603/215931277-614ae835-06a2-4533-a9c8-5f1601a35ddc.png)

**Comment by DfrostX** [comment] 2023-02-04 04:24
Well for me it does not pass the metadata to the display if I auto change launch in FS MPC-BE. HDR is off in statistics. The only way I can get the metadata to the display is to start minimised and go fullscreen manually.

Triggering "convert to HDR" does work,, but this is not what I want to do.

Not a big deal, I'm used to it by now, but I tought I would report it.

Appart from this minor issue, MPC-VR has been great for me, thanks!

**Comment by Aleksoid1978** [comment] 2023-02-04 05:04
Try this latest git version, maybe help.
[MpcVideoRenderer-0.6.4.1994_git2023.02.02-1167b3b.zip](https://github.com/Aleksoid1978/VideoRenderer/files/10607677/MpcVideoRenderer-0.6.4.1994_git2023.02.02-1167b3b.zip)

**Comment by DfrostX** [comment] 2023-09-15 22:08
Update on this. Even the newer versions are still behaving the same

I recently found out that Alt-Enter vs Ctrl-Enter have 2 different functions in MPC-BE. Seems like launch in FS is acting more like Alt-Enter (FS same res) than Ctrl-Enter (FS) and seem to ignore the autochange FS resolution of the monitor options. At least that is true when using passthroug HDR metadata to the display in MPC-VR .

So the solution I came up with is to use an autohotkey script that is triggered by the detection of MPC-BE.exe process, which is sendinput (Ctrl-Enter) with a slight delay off 100ms after detection.

Not the most elegant fix, but it works perfectly. I now have FS with the desired resolution + refresh rate change along the HDR metadata.

I'm putting it here in case it can be helpfull either in troubleshooting the issue or for other users

Thanks

**Comment by JTGaming** [comment] 2024-02-22 19:20
Is there anyone who'd be interested in testing out a fix?
I don't really use this combination of features myself, so would be good to get someone who is affected by this bug.
I just want to see how well it works for other people, if it crashes, etc.

**Comment by JTGaming** [comment] 2024-02-23 00:40
I've tried it out just now and sadly that does not seem to be the case.
It's labelled pretty poorly, it does not 'delay' the auto-change, but just pauses playback on launch for x seconds which does nothing.
As I said before, if anyone has an HDR screen and would like to be a beta tester, write a comment.

**Comment by JTGaming** [comment] 2024-02-23 02:05
Well if you decide to give it a go, here it is:
[MpcVideoRenderer.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14380939/MpcVideoRenderer.zip)
Obviously it works for me, but the whole HDR thing on windows is so janky, I wanna know if it even functions for other people.

**Comment by Fr0stX76** [comment] 2024-02-24 12:26
Well since this was my issue, I will test the built posted above and report back

And no, adding the delay does not fix it, as JTGAming wrote, the auto-change, just pauses playback on launch for x seconds which does nothing.

**Comment by Fr0stX76** [comment] 2024-02-24 12:33
@JTGaming, it works. It does take a bit longer for the image to apprear, around 2-3 seconds, but it fixes the issue. Its a keeper for me.

**Comment by NBruderman** [comment] 2024-02-24 12:58
@JTGaming can you make the PR for the fix?

**Comment by JTGaming** [comment] 2024-02-24 15:37
Yeah, this had me stumped for a good few days since there doesn't seem to be any documentation on these kinds of features from Microsoft. Took some trial and error to just get it to not crash instantly.
I'll clean up the code and open a pr later tonight.

**Comment by Fr0stX76** [comment] 2024-02-24 15:59
@JTGaming 

I just found a case were the renderer will not initiate.

If I use RTX video HDR, sometimes the renderer fails to initiate, in this case I get a blackscreen.

This actually is 100% reproduceable if I use a 4K SDR file with RTX HDR. On a 1080p SDR video, it fails maybe once out of 4.

I know this is a very specific scenario, but I tought I would report it.

**Comment by JTGaming** [comment] 2024-02-24 16:33
What option is your "windows hdr" setting on - is it "allow turn on", or "allow turn on and off"?

Also, just to get this right:
Your screen is in HDR mode, and when you play a 4K SDR video with RTX Video HDR on, it crashes on launch?

**Comment by JTGaming** [comment] 2024-02-24 18:09
Also, could you give this one a try?
[MpcVideoRenderer_no-fix.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14393881/MpcVideoRenderer_no-fix.zip)
I've disabled my code, but it's the latest build of source. It won't do anything for this bug, but I just want to see if it still crashes on your system - that way I can tell if it's my code that's causing issues, or if it's just RTX Video HDR being wonky.
Just use the same settings as you did for the above build that caused blackscreen.
I'm out of the country at the moment, so don't have an nvidia system to test on until next week.

**Comment by Fr0stX76** [comment] 2024-02-24 18:28
Ok did some more testing.

Windows display HDR setting on
Using "allow turn on"

You are right, using the no-fix built, I get the same result with the 4K SDR video.

With that said, with both built, disabling "launch in fullscreen" will lauch the video as expected (with RTX HDR), and double clicking to fullscreen will works as intended.

**Comment by JTGaming** [comment] 2024-02-24 18:33
Are you using MPC-HC, by any chance?

**Comment by Fr0stX76** [comment] 2024-02-24 18:34
Note: My 100ms script to Ctrl-Enter has the same result, but changing the delay to 250ms seems to fix it.

And no, I use MPC-BE

**Comment by JTGaming** [comment] 2024-02-24 18:39
Okay, I'll try to look into it when I'm back home in a day or two. Sounds more like an RTX Video HDR implementation issue then, if it still happens on the no-fix version.

Could you try turning on 16bit and use dithering in mpcvr? That used to fix some crashing for me, but it does have a performance impact.

**Comment by Fr0stX76** [comment] 2024-02-24 18:51
16bit float point + dithering works

**Comment by JTGaming** [comment] 2024-02-24 19:00
That's good to hear. That's what i use myself since mpc-hc likes to crash with HDR content often.
As long as you're not dropping frames and stuttering wildly (like my slow laptop for example), I'd recommend keeping 16bit+dither on for now.
I'll update this thread if i manage to reproduce and debug this crashing.

But just to reiterate, the fix works fine as long as rtx video hdr is not involved, yes?

**Comment by Fr0stX76** [comment] 2024-02-24 19:27
Correct, the build you posted fixes the original issue.

**Comment by Aleksoid1978** [comment] 2024-02-26 00:26
I checked it on my monitor (it allows you to choose 30 or 60 Hz) - everything switches correctly, switching modes in the MPC-BE works + HDR mode is turned on in the system in MPC VR.
In MPC-BE "launch in Fullscreen" is selected.

**Comment by JTGaming** [comment] 2024-02-26 01:19
Do you mean it works correctly with the build i provided, or that you do not have this issue on your system with original source code build?

**Comment by Aleksoid1978** [comment] 2024-02-26 01:25
I don't have issue with original code.

**Comment by Fr0stX76** [comment] 2024-02-26 01:49
Here are 2 screenshots:

I used the same settings for both screenshots, I only changed the renderer version between the latest nightly and JT's.

JT's code clearly does something my display likes better with MPC-BE option.

Nightly
![1](https://github.com/Aleksoid1978/VideoRenderer/assets/70845235/4592812c-462f-42bb-8462-1d6b6ce2f63f)

JT's
![2](https://github.com/Aleksoid1978/VideoRenderer/assets/70845235/3ac03494-f0de-4e5c-bbd2-2842ae5b51d5)

My settings:
![3](https://github.com/Aleksoid1978/VideoRenderer/assets/70845235/89dbddd1-9439-4756-811a-b517cf379784)

**Comment by Aleksoid1978** [comment] 2024-02-26 02:26
I can say that I use the same settings.
Perhaps it depends on the output device and how long it takes them to switch modes/frequencies and activate the HDR mode.

**Comment by Aleksoid1978** [comment] 2024-02-26 02:29
I double-checked it again by setting the options in MPC-BE and MPC VR 1:1 as in the screenshots above - everything switches perfectly.

So I don’t even know how to help in this situation. Even if someone provides code that “fixes” the situation, I will not be able to check it.

**Comment by JTGaming** [comment] 2024-02-26 04:56
Could you record a short screen capture of you opening a video with the debug overlay open? I'm interested to see if i could notice a reason for why you are not able to reproduce this bug.

Maybe OBS would work - i would just like to see the mpcvr debug menu as it goes from the stages of "opening file" to "final output".

**Comment by JTGaming** [comment] 2024-02-26 05:52
Since you have the code, could you breakpoint right before HandleHDRToggle() runs and show screenshots of the debug screen?
One before the HandleHDRToggle() runs, and one after the video starts playing.

**Comment by Aleksoid1978** [comment] 2024-02-26 06:01
![1](https://github.com/Aleksoid1978/VideoRenderer/assets/11625603/c36dcc2a-9015-453a-94be-401869552521)
![2](https://github.com/Aleksoid1978/VideoRenderer/assets/11625603/81b59af0-4d89-4e3f-869c-bbf38be3adfb)

Right before call **DisplayConfigSetDeviceInfo()** for set HDR mode.

**Comment by JTGaming** [comment] 2024-02-26 06:27
Okay, I'll be honest - I'm a bit stumped as to why it is not happening on your system.
For me, toggling hdr on via DisplayConfigSetDeviceInfo() just resets the refresh rate to the maximum my display can handle and doesn't keep it to the same one as it was on SDR.
Maybe it's a Samsung thing...

One last test I can think of:
Set your monitor to SDR 60Hz, and press Win+Alt+B to turn on HDR. Is your display in 60Hz or 30Hz?
Then, set your display to SDR 30Hz, and press Win+Alt+B to turn on HDR. What about now?

**Comment by Aleksoid1978** [comment] 2024-02-26 06:34
Always 60, HDR or SDR :)

**Comment by Aleksoid1978** [comment] 2024-02-26 06:44
> Okay, I'll be honest - I'm a bit stumped as to why it is not happening on your system.
> For me, toggling hdr on via DisplayConfigSetDeviceInfo() just resets the refresh rate to the maximum my display can handle and doesn't keep it to the same one as it was on SDR.

Ha - and you're right, it is. But - then my screen blinks again and the mode becomes correct, with the required frequency :)
![1](https://github.com/Aleksoid1978/VideoRenderer/assets/11625603/55eebb3a-fe91-45ff-99db-8d9f6c1c48de)

**Comment by Aleksoid1978** [comment] 2024-02-26 07:06
So - if there is a solution that does not reset the mode/frequency when HDR mode is activated, I can check it myself.

**Comment by JTGaming** [comment] 2024-02-26 07:07
Yeah, I'm not sure if it's a Windows issue, an MPC issue, or a VR issue anymore.
If i turn off "restore resolution on program exit' in MPC so that ChangeDisplaySettingsExW() gets called without the CDS_FULLSCREEN flag on, it works sometimes and i get correct refresh rate with hdr (but it likes to crash often too).

I've never gotten it to work with "restore resolution on program exit" turned on (which is default).
I wonder if it's your display turning the refresh rate back to 30Hz? Cause I am using the same nightly builds as you, so there shouldn't be any difference in code.

I guess the main issue here is that your setup fixes itself (SDR 60Hz -> SDR 30Hz from MPC -> HDR 60Hz from MPCVR -> HDR 30Hz from ???), but it doesn't do that for other people (for us it's only SDR 60Hz -> SDR 30Hz from MPC -> HDR 60Hz from MPCVR, thus the bug).

**Comment by Aleksoid1978** [comment] 2024-02-26 07:22
It turns out that yes - with the current code in MPC-BE (calling SetDispMode()) to set the screen mode - activating the HDR mode (even if done manually in the system settings) leads to the mode being reset.

**Comment by Aleksoid1978** [comment] 2024-02-26 07:57
Try this build MPC-BE
[mpc-be64.exe.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14401368/mpc-be64.exe.zip)

I changed the ChangeDisplaySettingsExW() call, but now with “restore resolution when exiting the program” enabled, if you “kill” the player process, the mode will not be restored. Otherwise, there seems to be no difference in switching screen modes.

**Comment by JTGaming** [comment] 2024-02-26 08:35
That seems to work from the few side-by-side comparisons i've done.

I did notice the 'not restoring refresh rate' thing if i kill the process via task manager, which doesn't happen with the fix i have in mpcvr itself, but your code in mpc-be is probably a more elegant fix for this issue.

**Comment by Aleksoid1978** [comment] 2024-02-26 09:21
Can you show how you fix ?

**Comment by JTGaming** [comment] 2024-02-26 09:40
I just left home, so i won't have access to the exact code for a couple hours, but the gist of it is:
Check display refresh rate before ToggleHDR() and compare it to after calling that.
If the refresh rate changed (which we don't want to happen), set refresh rate to what it was before ToggleHDR().

Not really fixing the issue, more just working around it, but I'm not sure there's a better way of doing it in mpcvr since there's no way to set refresh rate and hdr at the same time (like resolution and refresh rate, for example).

But at least it fixes this issue in mpcbe and mpchc too (which i use myself).

**Comment by Aleksoid1978** [comment] 2024-02-26 10:36
Better do all in MPC VR - so it's will be working with any player.
So - give me a patch, i'l look and test.

**Comment by Fr0stX76** [comment] 2024-02-26 11:29
I confirm, the MPCBE test build + latest nightly build also fixes the issue on my setup

**Comment by Aleksoid1978** [comment] 2024-02-26 11:45
Tomorrow I'll try modify VR.

**Comment by JTGaming** [comment] 2024-02-26 11:47
I'll be home in about an hour, so I'll publish the code then

**Comment by Aleksoid1978** [comment] 2024-02-27 00:33
Trying this build, with MPC-BE or MPC-HC.
[MpcVideoRenderer-0.7.2.2199_git2024.02.21-ab1a2ad.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14412760/MpcVideoRenderer-0.7.2.2199_git2024.02.21-ab1a2ad.zip)

**Comment by JTGaming** [comment] 2024-02-27 01:19
it works for me, but I've noticed that it takes a bit longer to switch back to normal when closing the player.
Your version goes: HDR 60Hz -> SDR 240Hz -> SDR 60Hz -> SDR 240Hz
whereas with the build in my pr, it just does: HDR 60Hz -> SDR 240Hz
besides that, it's the same.

**Comment by Aleksoid1978** [comment] 2024-02-27 01:24
That's right - when we turn off HDR mode, we can also “lose” the current display mode.
We can turn on/off HDR mode not only when going to full screen or opening a file, but for example when changing settings.

**Comment by Fr0stX76** [comment] 2024-02-27 02:36
The new MPC-VR build also fixed the issue (with the official release of MPC-BE)

**Closed** 2024-02-27 03:08 UTC

**Comment by JTGaming** [comment] 2024-02-27 14:32
Yes, I've thought that would be more ideal - instead of having the player change refresh rate and renderer change hdr status - you would have one or the other do both jobs.

Maybe just port the hdr toggling code from the renderer to the player? But that seems like more work that requires changing both codebases, not sure how that would play with other custom players/renderers.

**Comment by Aleksoid1978** [comment] 2024-02-27 21:30
People, stop fantasizing.
Nothing will be transferred anywhere. And if you don’t like the fact that it’s taking longer to switch HDR, uncheck the “restore resolution when exiting the program” checkbox in the player and you’ll be happy.
