### ISSUE TITLE
banding with D3D11 rendering

### ISSUE THREAD

**Issue by mightyhuhn** [Aleksoid1978/VideoRenderer#197] opened 2024-11-29 15:17 UTC
mpcVR produces heavy banding with D3D11.

mpcVR 0.8.7.2295
mpc-be 1.8.0

because it tries to render 10 bit i can not really share a screenshoot with 10 bit so this is the best i can do:
![image](https://github.com/user-attachments/assets/55e055d3-0971-4590-8c01-23ebef51f3cd)

settings used: 
![image](https://github.com/user-attachments/assets/5d7221c4-c2bd-48c4-a6ef-2199d5a49b6b)

the result is 8 bit none dithered.
source file: https://www.bealecorner.org/red/test-patterns/Gradient-16bit.png 
d3d9 dithers correctly.

**Comment by v0lt** [comment] 2024-11-30 17:53
> mpcVR produces heavy banding with D3D11.

I can't reproduce the problem. I recommend restarting playback after changing renderer settings.

> d3d9 dithers correctly.

In D3D9 mode, the video renderer outputs 8-bit to the texture.

**Comment by v0lt** [comment] 2024-11-30 18:01
Maybe I have bad eyesight or a display that doesn't have enough contrast.
I can see the dithering working when converting Int10/Float16 to Int8. But I don't see the effect of dithering when converting Float16 to Int10.

**Comment by mightyhuhn** [comment] 2024-11-30 20:37
yes but i double check such issues by also checking madVR and mpv. both say they output 10 bit and there is no banding that looks like 8 bit rounded.

and yes the screenshoot is 8 bit dithered for some reason.
i can easily simulate what is shown. 

the DWM could be at fault but that would also fail the other to renderer.

> Maybe I have bad eyesight or a display that doesn't have enough contrast. I can see the dithering working when converting Int10/Float16 to Int8. But I don't see the effect of dithering when converting Float16 to Int10.

the error looks like 8 bit rounded.

with the shared pattern 10 bit rounded should still be visible to the naked eye but it's quite hard to see.
i only know of restarting the player to change between d3d9 and d3d11 so that should no be the issue.
i also checked 8 10 16 bit with and without dithering all look the same. and 8 shouldn't stand a chance.

**Comment by mightyhuhn** [comment] 2024-11-30 21:06
i found something very very odd here.
if you start the player with 8 bit internal and change it to 16 bit the banding will disappear but is back when you restart the player with the 16 bit option still selected.

**Comment by v0lt** [comment] 2024-12-08 17:57
To save the displayed video frame as 48-bit PNG, you will need:
Display shown in 10-bit mode.
MPC-BE x64 1.8.2.12+
MPC Video Renderer 0.9.0.2327+

First, save the original video frame in the menu (File > Save image). Select the PNG format and save it in the desired folder.
After that, you can save the displayed video frames in PNG 48 bit using the Shift+F5 key. The results will be in the previously selected folder.

**Comment by mightyhuhn** [comment] 2024-12-08 22:45
this screenshoot does not contain banding and it at least 10 bit.
![Gradient-16bit png_snapshot_00 00_ 2024-12-08_23 29 10](https://github.com/user-attachments/assets/1f2fe6ac-e430-4a2a-a308-32b7d41c73de)

opening the screenshoot with mpcVR will show the banding again it is clean in madVR proofing this.
the issue is still there.

i will update my window 10 version currently 19045 but why would only mpcVR care about that and other player work just fine...

**Comment by mightyhuhn** [comment] 2024-12-08 22:54
that's the newest version well... ahhh i try a couple of nvidia driver.

**Comment by Aleksoid1978** [comment] 2024-12-09 02:41
madVR work with D3D9 and only output in D3D11.

**Comment by Aleksoid1978** [comment] 2024-12-09 02:45
Why texture 16bit ?

**Comment by mightyhuhn** [comment] 2024-12-09 03:22
because you would end up with banding any other way?

**Comment by Aleksoid1978** [comment] 2024-12-09 04:11
I have a monitor with "true" 10 bit output, I don't see any difference between the picture on 10 or 16 bit textures.

**Comment by Aleksoid1978** [comment] 2024-12-09 04:13
What screen do you have?

**Comment by Aleksoid1978** [comment] 2024-12-09 04:21
[Gradient-16bit.png - MPC-BE x64 1.8.2.12 dev 09.12.2024 14_16_57.zip](https://github.com/user-attachments/files/18056295/Gradient-16bit.png.-.MPC-BE.x64.1.8.2.12.dev.09.12.2024.14_16_57.zip)

Here I made a screenshot using Windows in HDR mode - the colors during viewing are distorted, but it correctly retained the bit depth.
And as you can see, there is no banding.

**Comment by mightyhuhn** [comment] 2024-12-09 04:28
samsung S90C.

the screenshoot function works perfectly.

and i found something new this happens with discard not with flip!

**Comment by Aleksoid1978** [comment] 2024-12-09 04:49
> and i found something new this happens with discard not with flip!

Use Flip.

**Comment by mightyhuhn** [comment] 2024-12-09 05:11
is this fixed: https://forum.doom9.org/showpost.php?p=2007769&postcount=10733

**Comment by Aleksoid1978** [comment] 2024-12-09 05:27
> is this fixed: https://forum.doom9.org/showpost.php?p=2007769&postcount=10733

It's already fixed.

**Comment by Aleksoid1978** [comment] 2024-12-09 05:32
With Discard - yes, we have banding. It's look's like issue in D3D11.

**Closed by Aleksoid1978** 2024-12-09 05:32 UTC

**Comment by v0lt** [comment] 2024-12-09 09:01
I made a test image 2048x1024 with 4 stripes. This was enough to fill the gradient with 8192 values, which corresponds to 13-bit. Saved in PNG 48-bit (16-bit per channel).

![gradient13bit](https://github.com/user-attachments/assets/0e55fc54-a303-42a7-b20a-91808525df59)

**Comment by mightyhuhn** [comment] 2024-12-09 17:29
> I made a test image 2048x1024 with 4 stripes. This was enough to fill the gradient with 8192 values, which corresponds to 13-bit. Saved in PNG 48-bit (16-bit per channel).
> 
> gradient13bit.png ![gradient13bit](https://private-user-images.githubusercontent.com/2035946/393767461-0e55fc54-a303-42a7-b20a-91808525df59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjUwODYsIm5iZiI6MTczMzc2NDc4NiwicGF0aCI6Ii8yMDM1OTQ2LzM5Mzc2NzQ2MS0wZTU1ZmM1NC1hMzAzLTQyYTctYjIwYS05MTgwODUyNWRmNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTcxOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQ3ZTAwZWM1OTc0MzBiNWNhYzRiMGM2NmNkNTYzMDMzMzRjNGE2Zjk5ZGEyZjEwYzgwMTFlZGQ5YzE4NTE1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Af8Fd9mcrpG9hSfkNuS8b9njlJ2SJ0rUstHIqs4sCYk)

how does the new 16 bit screenshoot function turn the 10 bit to 16 bit? how is your 13 bit turned to 16?


> If the screenshot doesn't have the banding then perhaps the bug is in DWM?

yes that's why i'm testing GPU driver. the oddest thing is it can do it correctly if you set it to 8 bit internal restart and switch to 16 bit...



> Also, Madvr is able to detect the native bitdepth of your monitor, and apply dithering to that depth. So it can for example output 10bit but dither at 8bit. That is useful for monitors that have no/bad dithering. There is a setting to overrule detected bitdepth for testing (devices > properties). Check what it detect for your TV and if it detects 8bit, see if you get banding when overriding to 10.

this is nearly for sure a way to avoid an older nvidia bug full auto detection only works with nvidia edid works partially. with AMD i can throw 10 bit at the GPU driver on a display where i send 6 bit to the display with nvidia it will not allow that. madVR using AMD has no clue about this and just does it's thing. and yes sending lower bit deep to bad displays is a very useful thing.

i test this the S90C does not care. i personally used 8 bit for the majority of my life because it had less banding with pretty much every TV i owned before.

**Comment by mightyhuhn** [comment] 2024-12-10 04:45
i'm asking if you added 3 0 to reach 16 or took the first 3 bit and put them at the end stuff like that.
not if 16 bit is possible...

**Comment by v0lt** [comment] 2024-12-10 05:45
I made a gradient from zero to maximum with a step of 8. Accordingly, the least significant bits were not used.

You can see the pixel values ​​yourself in [ImLab](https://sourceforge.net/projects/imlab/) or another editor with full support for RGB 16-bit per channel.
