### ISSUE TITLE
Deinterlacing not working well on high frequency displays (144 Hz)

### ISSUE THREAD

**Issue by bobdig** [Aleksoid1978/VideoRenderer#45] opened 2022-01-31 06:36 UTC
I am a user of MPC-HC and one gripe I have with the now default MPC Video Renderer is how unsmooth the deinterlacing is still looking. I "tested" this with a nvidia 1060 and 3060 mobile on a 144 Hz Screen (monitor and laptop). The result is always the same, with EVR(CP) it is much smoother. I wish we could get some [progress](https://github.com/clsid2/mpc-hc/issues/631) with that.

**Comment by Aleksoid1978** [comment] 2022-02-01 01:17
Developers don't have screen with high refresh rate and can't test/debug. On 60 Hz all is perfect.

**Comment by bobdig** [comment] 2022-02-01 06:32
Back in the day I could see the difference even with 60 Hz, if I read correct. And EVR(CP) can't do frame interpolation I guess, so the reason must be something different. Maybe doing a life capture will reveal it, will try that.

**Comment by bobdig** [comment] 2022-02-01 09:47
So I did a capture and you are right, comparing frame by frame there is no difference @ 60 Hz, but with 144 Hz there are some extra frames with the EVR(CP). So my hope is one day you get a high refresh monitor.

**Comment by clsid2** [comment] 2022-02-01 12:59
Are those extra frames different, or just repeats?

Playing 50 fps at 144 Hz means that 44 of those frames are displayed 3 times, and 6 frames 2 times.

**Comment by bobdig** [comment] 2022-02-01 14:39
@clsid2 Those extra frames are different, hence the better visuals.

**Comment by bobdig** [comment] 2022-02-01 14:55
@clsid2 Your question made me test something again. To me it is looking like that the deinterlacing with MPCVR is worse 144 Hz then it is with 60 Hz. I searched for such a extra frame and I found it in MPCVR 60 Hz, EVR(CP) 144 Hz but not in MPCVR 144 Hz (haven't searched in EVR(CP) 60 Hz)
So that is probably explaining it, there must be sum bug that deinterlacing with EVR(CP) 144 Hz is worse then with 60 Hz.

**Comment by clsid2** [comment] 2022-02-01 15:00
Can you also test with madvr?

**Comment by bobdig** [comment] 2022-02-01 15:01
@clsid2 I never use madvr and I have not installed it.

**Comment by bobdig** [comment] 2022-02-01 15:13
@clsid2 I could but the problem is probably something hard coded or a bad divider, making 144 looking worse then 60.
And those recordings are janky as it gets, it is really no fun comparing them...

**Comment by clsid2** [comment] 2022-02-01 15:18
If you can see any pattern on how frames are repeated in both recordings, then that might give a clue about what is happening and what is different.

**Comment by bobdig** [comment] 2022-02-01 15:23
Those recordings have different time stamps so it is really no fun. Also you can't look at those colored blocks because they are added artificially, you have to look at the presenters movements. There you can see, that some frames are missing in MPCVR 144.
Here is a [Link](https://mega.nz/file/moURwI7T#iMX127XQULJUykOaLdYIWL_vN5z9l06a5xNdOMqQMAk), pw is my username here.

**Comment by clsid2** [comment] 2022-02-01 16:02
Have you tried with Direct3D11 in MPCVR?
You can also try deinterlacing with LAV Video Decoder, to see if that gives better results.

**Comment by clsid2** [comment] 2022-02-01 16:18
The whole point of those suggestions are to compare with different settings, to see if that makes any difference in behavior of MPCVR.

**Comment by bobdig** [comment] 2022-02-01 16:20
I can watch it several times and I hope my feelings won't be wrong, but I have enough of frame peeping one by one. :)

**Comment by v0lt** [comment] 2022-02-06 06:51
I previously wrote that deinterlacing will not work well in MPC VR on high frequency displays. You have checked and confirmed this. Thank you.

In the first post, you didn't specify the version of MPC VR. I will ignore such bug reports in the future.

**Comment by bobdig** [comment] 2022-02-06 06:57
It is a persistent problem. I am user of the klite codec pack, so the version on my system of today is: MPC Video Renderer 0.5.7.1812 (git-2022.01.10-7488a3c) x64.

**Comment by eebssk1** [comment] 2022-11-03 11:24
Can confirm MPCVR is unsmooth on 144hz display. Changed to EVR and everthing's fine.

**Comment by NBruderman** [comment] 2023-11-10 13:08
I actually have a 144Hrz sceen, and recently I thought about switching from MadVR TO MPCVR, but should I do it?
Is this a major issue in day to day viewing experience?

**Comment by v0lt** [comment] 2023-11-10 14:41
> Is this a major issue in day to day viewing experience?

We do not have the ability and desire to watch your video on your display.

**Comment by JTGaming** [comment] 2024-02-10 12:50
Is this the bug you are referring to?
Where, when enabling the 'double the frame rate when deinterlacing' option (which is enabled by default), the frametimes fluctuate wildly and aren't being presented in a steady fashion?
![frametime variance](https://github.com/Aleksoid1978/VideoRenderer/assets/38790084/0028ba5e-2f25-4440-8153-990add211b3f)

If yes, could you try turning that feature off and seeing if that at least helps somewhat? Also, could you provide some screenshots of the debug screen (like the one above) when the issue is occurring?

**Comment by janos666** [comment] 2024-02-10 18:30
Stupid question: Why don't you auto-switch to 120Hz for i60 content anyway? Or is anything wrong with i60 at 120Hz as well?

**Comment by JTGaming** [comment] 2024-02-10 19:33
So what you're saying is, the frametime graph looks smooth on your end with interlaced content, yet it still feels janky to you?

**Comment by zhallgato** [comment] 2024-02-17 21:16
@JTGaming I also have this issue with an 240Hz monitor.

Here is the screenshot of the debug screen when this issue occurs to me on 240Hz:

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/20367772/cd63bc69-8634-4faf-a572-a50119c83644)

If I disable the 'double the frame rate when deinterlacing' option, then it looks like this:

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/20367772/7db495ae-59d4-4319-91bd-2d5419546763)

This helps with the issue, because there are no spikes, but the overall experience is not smooth, because there is less frames as @bobdig already mentioned.

Also if I switch back to 60Hz the graph looks okay again and the playback is smooth:

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/20367772/6d03805a-978e-45a7-9bdf-a0bf32299bb1)

**Comment by JTGaming** [comment] 2024-02-17 22:30
@zhallgato okay, yeah, that looks like what I expected and experienced on my own system.
Would you mind testing this build out and seeing how interlaced content feels: https://github.com/JTGaming/VideoRenderer/releases/tag/0.7.1v6

It should be auto-enabled, but just double check that "Frame Synchronization" is on in MPC VR settings (you can also use this to quickly toggle between having the fix on or off, which might help to compare).

NOTE: you might want to take a screenshot of your current settings, as my build has some UI changes. It shouldn't mess with stuff if you already have a profile, but if you press the 'default' button then it will be different.

**Comment by zhallgato** [comment] 2024-02-17 22:52
@JTGaming I tested the build, and I can confirm the issue is fixed. 

The interlaced content playback is perfectly smooth on 240 Hz. 

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/20367772/c647afe4-39ee-4506-8233-236c399856ec)

**Comment by NBruderman** [comment] 2024-02-17 23:01
@JTGaming it seems to work! Can you create a pull request with the fix?
So it can finally be fixed on the main repo

**Comment by JTGaming** [comment] 2024-02-17 23:02
That's good to hear. If anyone else would like to test it out themselves, please report back your findings here (preferably with screenshots of the frametime graph).

I'll try and submit a PR sometime later when I am free to get this fixed and into the hands of everyone.

**Comment by Aleksoid1978** [comment] 2024-02-18 09:01
Trying this build.
[MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14321785/MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205.zip)

**Comment by Aleksoid1978** [comment] 2024-02-18 09:34
> > Trying this build. [MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14321785/MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205.zip)
> 
> Looking good to me, thank you.

How does it compare to the version from JTGaming?

**Comment by Aleksoid1978** [comment] 2024-02-18 09:43
Another build with very small difference
[MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14321918/MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205.zip)

**Comment by Aleksoid1978** [comment] 2024-02-18 09:44
What's bad ? What's compare ?

**Comment by Aleksoid1978** [comment] 2024-02-18 10:03
Why uninstall ? Replace files from archive.

**Comment by Aleksoid1978** [comment] 2024-02-18 11:48
Another version
[MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205-3.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14322308/MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205-3.zip)

**Comment by zhallgato** [comment] 2024-02-18 12:12
@Aleksoid1978 

I also tested the third version, and here are my results:

It looks much better than the original master version, but not as smooth as @JTGaming version.

Also I got sometimes a spike in the graph which resulted in some stuttering:

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/20367772/9c98d618-bb0a-42b1-a7bd-b3579fdaebef)

**Comment by Aleksoid1978** [comment] 2024-02-18 12:21
[MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205-4.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14322448/MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205-4.zip)

**Comment by NBruderman** [comment] 2024-02-18 12:22
> >  but not as smooth as @JTGaming version.
> 
> @zhallgato  Do you have a favorite, JTGaming version or EVR CP? Maybe we can have a discussion @JTGaming but I can not open an "issue" there. It would be nice to solve this problem once and for all in the best way possible.

@JTGaming said in their PR that the solution he posted to here covers around 90% of the problem, as he wanted to keep the code simple, because the one he implemented in his fork is much more complicated, and covers more edge cases. Maybe it's worth using a more comprehensive solution here too, in order to end this issue once and for all.

**Comment by zhallgato** [comment] 2024-02-18 12:25
Do you have a favorite, JTGaming version or EVR CP?

@bobdig Sorry, but I don't use EVR CP. I use MPCVR for everything except for the interlaced content, because of the above-mentioned issue.
For the interlaced content I use madvr, because that looked the best option for me until yesterday.

But after testing JTGaming version I think I will be able to switch to MPCVR entirely, because it looked to me as smooth as madvr.

**Comment by zhallgato** [comment] 2024-02-18 12:34
@Aleksoid1978 

The fourth version looks better there are no spikes:

![image](https://github.com/Aleksoid1978/VideoRenderer/assets/20367772/00be31f4-4ca4-4ab3-81d1-ed59a41a8299)

**Comment by zhallgato** [comment] 2024-02-18 12:52
I test it without it and just simply watch the video. :)

But JTGaming asked the graph before, so I thought it is useful for you if I keep posting. (but I won't do it anymore then)

So as I said before the fourth version looks good enough, I don't see too much difference compared to JTGaming version (it feels like JTGaming version is still a little bit smoother, but maybe I'm just imagining it)

**Comment by v0lt** [comment] 2024-02-18 16:25
If you have not enabled WaitForVBlank, then the graph most likely does not show small frame jitters.
If you enable WaitForVBlank, the graph will be closer to reality, but users are scared of the sawtooth graph.

The most reliable way to understand whether there is a problem is to see it yourself without displaying statistics on a suitable video. It also makes sense to compare with WaitForVBlank disabled and enabled.

**Comment by Aleksoid1978** [comment] 2024-02-18 23:42
"Финальная" версия.
[MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205-5.zip](https://github.com/Aleksoid1978/VideoRenderer/files/14324902/MpcVideoRenderer-0.7.2.2195_git2024.02.15-192e205-5.zip)

**Comment by JTGaming** [comment] 2024-02-19 01:28
Seems fine enough from my testing.
I'm guessing you're doing the waiting inside the Render() function itself, right before the call to Present()?
Interested to see the code once you push your commit.

**Comment by Aleksoid1978** [comment] 2024-02-19 01:31
Yes - calculate diff and sleep if need just before call present().

**Comment by NBruderman** [comment] 2024-02-20 12:05
@JTGaming the commit is out

https://github.com/Aleksoid1978/VideoRenderer/commit/a2fb8ea0fd87a7a7eedd26c602a1495ed6efcfa5

**Comment by JTGaming** [comment] 2024-02-20 20:08
Seems like the issue is finally fixed.
If anyone would like to double-check and confirm that, then this issue could finally be closed.

**Comment by zhallgato** [comment] 2024-02-21 15:26
I double-checked, and I can also confirm that the problem is fixed. This issue can be closed.

**Closed** 2024-02-21 21:02 UTC

**Comment by v0lt** [comment] 2024-03-01 18:20
I made a slightly modified version.
[mpcvr-0.7.2.2207_minimizing_sleep_calls_1.zip](https://disk.yandex.ru/d/aafl_2VKQDkFTw)
This version will not call Sleep if there is less than half of the display refresh interval left before presentation time.
